global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: aula
  static_configs:
  - targets:
    # - 192.168.1.107:3000 
    - 192.168.1.103:3000  #mac
- job_name: servidor
  static_configs:
  - targets:
    # - 192.168.1.107:9100 
    - 192.168.1.103:9100  #mac